### ISSUE TITLE
Error in MCP Server gathering Keycloak stats

### ISSUE THREAD

**Issue by david-martin** [feedhenry/mcp-standalone#150]
ERRO[5460] unexpected error: failed to gather metrics for service keycloakfailed to make request to keycloak http://http://keycloak-myproject.192.168.37.1.nip.io/auth/realms/master/protocol/openid-connect/token: Post http://http//keycloak-myproject.192.168.37.1.nip.io/auth/realms/master/protocol/openid-connect/token: dial tcp: lookup http on 208.67.222.222:53: no such host 

Looks like a double protocol being inserted somewhere when the url is passed around
(cc @maleck13 )

**Comment by david-martin** [comment]
@aidenkeating I believe this was fixed by #177 
Would you agree?

**Comment by aidenkeating** [comment]
Yep I would
