### ISSUE TITLE
add admin user with edit access during installation

### ISSUE THREAD

**Issue by maleck13** [feedhenry/mcp-standalone#184]
Currently we use the ```system:admin``` user and the ```developer``` user. However the ```system:admin``` user cannot log in via the UI.

It would be nice to be able to login as an admin to look at other namespaces such as the service catalog and ansible-service-broker

Currently I do this by login in as ```admin:admin``` through the UI. This creates a new user with no access. So then as the system:admin user I run

```oc adm policy add-cluster-role-to-user edit admin```

Doing this as part of the installation set up would be useful

**Comment by david-martin** [comment]
@maleck13 Agreed this could be useful as I've ran that command myself many times.
I'd recommend including it for the 'local dev' setup only.
This may be a good one to discuss with the tooling guys where we want different ways of installing e.g. local dev, local not dev, remote...
