### ISSUE TITLE
Use less instead of sass

### ISSUE THREAD

**Issue by david-martin** [feedhenry/mcp-standalone#20]
to remove the dependency on ruby (and the `compass` gem) for local development.
Currently, there is 1 sass file https://github.com/feedhenry/mcp-standalone/blob/master/web/app/styles/main.scss

Suggesting using https://github.com/gruntjs/grunt-contrib-less or similar module to dynamically serve compiled css for local development with `grunt serve`, and to build css with `grunt build` task.

**Comment by david-martin** [comment]
@maleck13 @jasonmadigan This one make sense to you?

**Comment by jasonmadigan** [comment]
Yes, makes sense. One less environmental dependency, and LESS has a comparatively rich feature-set for our needs I would say.
