### ISSUE TITLE
local setup instructions won't work with when docker hub password contains exclamation "!"

### ISSUE THREAD

**Issue by finp** [feedhenry/mcp-standalone#202]
should we warn users to set dockerhub password with only alphanum characters?

**Comment by maleck13** [comment]
No this seems like a bug

**Comment by aidenkeating** [comment]
@finp @maleck13 I can't seem to reproduce this, changed my password temporarily but everything worked fine. Will take a closer look tomorrow.

**Comment by aidenkeating** [comment]
@finp Thanks for your help on tracking this down.

Sounds like you were referring to this section (https://github.com/feedhenry/mcp-standalone/blob/master/docs/walkthroughs/local-setup.adoc#useful-bash-function) and using special characters here.

This issue doesn't occur when using the `installer/install.sh` script which we now recommend in the local setup doc. You can also use that bash function but escape the special characters.

Are you happy for this to be closed off?

**Comment by finp** [comment]
@aidenkeating  I'm happy! close it!
