### ISSUE TITLE
check that downloaded version of oc command is being run by the installer

### ISSUE THREAD

**Issue by mmurphy** [feedhenry/mcp-standalone#221]
The installer downloads the correct version of oc, however it may run a different version of oc if it appears in the PATH before the downloaded and installed version, so it should check that the version it's running is the one that is required
e.g. 
```
wget https://github.com...../oc-$VERSION.tgz
MYVERSION=`oc version`
if not matching("$MYVERSION", "$VERSION") then
   error "there is a different version of oc installed in your environment, please remove the old version"
   error "$(which oc)"
"

or maybe even simply
if $(which oc) != "/usr/local/bin/oc"

**Comment by maleck13** [comment]
Yes agree this sounds like a good idea. 
Another option would be to prompt the user during the installation and ask where they want to put the oc tool (with a default location of /usr/local/bin) then use that location for each of our following actions.

ping @aidenkeating

**Comment by aidenkeating** [comment]
@maleck13 Yep I think your suggestion makes sense. Will assign this to myself.

**Comment by mmurphy** [comment]
I don't mind if the installer asks the user, however after downloading we should still check to ensure that the correct version is being run
