### ISSUE TITLE
add mobile app display name 

### ISSUE THREAD

**Issue by maleck13** [feedhenry/mcp-standalone#24]
The app is currently backed by a configmap. So the name needs to match:
```
'[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'
```
This mean the name can't have spaces in it.

Having a displayName field would allow for setting a name that makes more sense to the end user.

**Comment by david-martin** [comment]
App type and Name field: https://github.com/feedhenry/mcp-standalone/blob/fdbdade2f08305487c1c0ed4be10651f0f2765a4/pkg/mobile/types.go#L13
