### ISSUE TITLE
Installer error

### ISSUE THREAD

**Issue by pb82** [feedhenry/mcp-standalone#61]
The installer currently fails with `ERROR! the role 'openshift-origin-client-tools' was not found`. It's referenced in https://github.com/feedhenry/mcp-standalone/blob/master/installer/playbook.yml#L6 but there is no such role.

The README states that the `oc` client tools have to be installed on the system, so should this role be removed from playbook.yml?

I'm not very familiar with ansible and I might do it completely wrong. In that case feel free to close the issue.

**Comment by aidenkeating** [comment]
Hey @pb82 

You'll need to run `ansible-galaxy install -r requirements.yml` from the `installer` directory. There are a few other prerequisites for the MCP, you can find them here https://github.com/feedhenry/mcp-standalone#prerequisites
