### ISSUE TITLE
create walkthrough for non development setup

### ISSUE THREAD

**Issue by maleck13** [feedhenry/mcp-standalone#94]
For someone who does not want to develop the MCP but rather just wants to try it out, we should have a walkthrough that uses the installer, but then takes them only through the OpenShift UI or OC tool

**Comment by david-martin** [comment]
@maleck13 Does https://github.com/feedhenry/mcp-standalone/blob/master/docs/walkthroughs/local-walkthrough.md satisfy this issue?

**Comment by maleck13** [comment]
Yes
